import { StyleSheet, Dimensions } from 'react-native';

const { height } = Dimensions.get('window');

export default StyleSheet.create({
    scrollContainer: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: 40, // Add padding at bottom
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f5f5f5',
        padding: 20,
    },
    envBadge: {
        position: 'absolute',
        top: 10,
        left: 10,
        backgroundColor: '#ff4757',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
        zIndex: 1000,
    },
    envBadgeText: {
        color: 'white',
        fontSize: 10,
        fontWeight: 'bold',
    },
    langToggle: {
        position: 'absolute',
        top: 50,
        right: 20,
        padding: 10,
        backgroundColor: '#fff',
        borderRadius: 20,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    langText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
    },
    title: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 10,
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 18,
        color: '#666',
        marginBottom: 30,
    },
    city: {
        fontSize: 20,
        marginBottom: 20,
        color: '#444',
        textAlign: 'center',
        fontWeight: '600',
    },
    aqiCircle: {
        width: 180,
        height: 180,
        borderRadius: 90,
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: 20,
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    aqiText: {
        fontSize: 64,
        fontWeight: 'bold',
        color: '#fff',
    },
    aqiLevel: {
        fontSize: 24,
        fontWeight: 'bold',
        marginVertical: 10,
    },
    healthTip: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginVertical: 15,
        paddingHorizontal: 20,
        fontStyle: 'italic',
    },
    error: {
        color: '#ff4444',
        marginVertical: 10,
        textAlign: 'center',
        fontWeight: '600',
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginVertical: 10,
        width: '100%',
        flexWrap: 'wrap',
    },
    actionButton: {
        backgroundColor: '#ff7e00',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 25,
        margin: 5,
        elevation: 3,
        minWidth: 100,
        alignItems: 'center',
    },
    actionButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    infoButton: {
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderRadius: 20,
        margin: 5,
        elevation: 2,
        minWidth: 90,
        alignItems: 'center',
    },
    infoButtonText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: '600',
        textAlign: 'center',
    },
    dominantContainer: {
        marginTop: 20,
        padding: 12,
        backgroundColor: '#f0f0f0',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#ddd',
    },
    dominantText: {
        fontSize: 14,
        color: '#555',
        textAlign: 'center',
    },
    loadingContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 40,
    },
    loadingText: {
        marginTop: 20,
        fontSize: 16,
        color: '#666',
    },
    // Stations Preview
    stationsPreview: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 15,
        marginTop: 20,
        width: '100%',
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    stationsPreviewTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 10,
    },
    previewStations: {
        marginTop: 5,
    },
    previewStation: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    previewDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
        marginRight: 10,
    },
    previewText: {
        flex: 1,
        fontSize: 14,
        color: '#555',
    },
    previewAQI: {
        fontSize: 14,
        fontWeight: 'bold',
        marginLeft: 10,
        minWidth: 30,
        textAlign: 'right',
    },
    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: 'white',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 20,
        maxHeight: height * 0.85,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        paddingBottom: 15,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
    },
    closeButton: {
        fontSize: 18,
        color: '#ff7e00',
        fontWeight: 'bold',
        padding: 5,
    },
    section: {
        marginBottom: 20,
        padding: 15,
        backgroundColor: '#f9f9f9',
        borderRadius: 10,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 10,
    },
    pollutantRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    pollutantLabel: {
        fontSize: 14,
        color: '#666',
        flex: 2,
    },
    pollutantValue: {
        fontSize: 14,
        fontWeight: '600',
        flex: 1,
        textAlign: 'right',
    },
    infoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 6,
    },
    infoLabel: {
        fontSize: 14,
        color: '#666',
    },
    infoValue: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
    },
    healthSection: {
        backgroundColor: '#e8f4fd',
        padding: 15,
        borderRadius: 10,
        marginBottom: 20,
    },
    healthText: {
        fontSize: 14,
        color: '#333',
        lineHeight: 20,
    },
    forecastTable: {
        marginTop: 20,
        backgroundColor: '#f9f9f9',
        borderRadius: 10,
        padding: 15,
    },
    tableHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderBottomWidth: 2,
        borderBottomColor: '#ddd',
        paddingBottom: 10,
        marginBottom: 10,
    },
    tableHeaderText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#333',
        flex: 1,
        textAlign: 'center',
    },
    tableRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    tableCell: {
        fontSize: 12,
        color: '#555',
        flex: 1,
        textAlign: 'center',
    },
    // Current Location Card in Modal
    currentLocationCard: {
        backgroundColor: '#f8f9fa',
        borderRadius: 12,
        padding: 15,
        marginBottom: 20,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    currentLocationTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 10,
    },
    currentAQIBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 25,
        minWidth: 150,
        justifyContent: 'center',
    },
    currentAQIText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        marginRight: 10,
    },
    currentAQILevel: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    // Stations List
    stationsList: {
        paddingBottom: 20,
    },
    stationsCount: {
        fontSize: 14,
        color: '#666',
        marginBottom: 15,
        textAlign: 'center',
        fontStyle: 'italic',
    },
    stationCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 15,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#f0f0f0',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    stationHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    stationIndex: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: '#e3f2fd',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    stationIndexText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1976d2',
    },
    stationInfo: {
        flex: 1,
    },
    stationName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 4,
    },
    stationDistance: {
        fontSize: 12,
        color: '#666',
    },
    stationAQISection: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    aqiBadge: {
        paddingHorizontal: 20,
        paddingVertical: 8,
        borderRadius: 20,
        minWidth: 80,
        alignItems: 'center',
    },
    aqiValue: {
        color: '#fff',
        fontSize: 20,
        fontWeight: 'bold',
    },
    aqiLevelText: {
        fontSize: 14,
        color: '#555',
        fontWeight: '600',
    },
    stationFooter: {
        borderTopWidth: 1,
        borderTopColor: '#f5f5f5',
        paddingTop: 10,
    },
    stationCoordinates: {
        fontSize: 11,
        color: '#888',
        textAlign: 'center',
    },
    noStationsContainer: {
        padding: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    noStationsText: {
        fontSize: 16,
        color: '#999',
        textAlign: 'center',
    },
    backButton: {
        backgroundColor: '#6c757d',
        paddingVertical: 12,
        borderRadius: 25,
        alignItems: 'center',
        marginTop: 20,
    },
    backButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
});
