import { StyleSheet, Dimensions, Platform } from 'react-native';
import colors from './colors';

const { width, height } = Dimensions.get('window');
const isWeb = Platform.OS === 'web';

export default StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: colors.background,
    },
    scrollContainer: {
        flex: 1,
        backgroundColor: colors.background,
        ...(isWeb && {
            height: '100vh',
            overflowY: 'auto',
        }),
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: 40,
        ...(isWeb && {
            minHeight: '100vh',
        }),
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.background,
        padding: 20,
        ...(isWeb && {
            width: '100%',
            maxWidth: 800,
            marginHorizontal: 'auto',
        }),
    },
    header: {
        alignItems: 'center',
        marginBottom: 30,
        paddingTop: 20,
    },
    mainContent: {
        flex: 1,
        padding: 20,
        alignItems: 'center',
    },
    envBadge: {
        position: 'absolute',
        top: 10,
        left: 10,
        backgroundColor: colors.envBadge,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
        zIndex: 1000,
    },
    envBadgeText: {
        color: colors.white,
        fontSize: 10,
        fontWeight: 'bold',
    },
    langToggle: {
        position: 'absolute',
        top: 50,
        right: 20,
        padding: 10,
        backgroundColor: colors.surface,
        borderRadius: 20,
        ...(isWeb && {
            position: 'fixed',
            cursor: 'pointer',
            boxShadow: '0px 2px 6px rgba(0,0,0,0.15)',
        }),
    },
    langText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.text,
    },
    title: {
        fontSize: 32,
        fontWeight: 'bold',
        color: colors.text,
        marginBottom: 10,
        textAlign: 'center',
    },
    // Search
    searchRow: {
        flexDirection: 'row',
        maxWidth: 400,
        width: '100%',
        marginBottom: 12,
        alignItems: 'center',
    },
    searchInput: {
        flex: 1,
        backgroundColor: colors.surface,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: colors.border,
        marginRight: 8,
    },
    subtitle: {
        fontSize: 18,
        color: colors.textMuted,
        marginBottom: 30,
        textAlign: 'center',
    },
    city: {
        fontSize: 20,
        marginBottom: 20,
        color: colors.textSecondary,
        textAlign: 'center',
        fontWeight: '600',
    },
    aqiCircle: {
        width: 180,
        height: 180,
        borderRadius: 90,
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: 20,
        ...(isWeb && {
            boxShadow: '0px 4px 12px rgba(0,0,0,0.25)',
        }),
    },
    aqiText: {
        fontSize: 64,
        fontWeight: 'bold',
        color: colors.white,
    },
    aqiLevel: {
        fontSize: 24,
        fontWeight: 'bold',
        marginVertical: 10,
    },
    healthTip: {
        fontSize: 16,
        color: colors.textMuted,
        textAlign: 'center',
        marginVertical: 15,
        paddingHorizontal: 20,
        fontStyle: 'italic',
    },
    error: {
        color: colors.danger,
        marginVertical: 10,
        textAlign: 'center',
        fontWeight: '600',
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginVertical: 10,
        width: '100%',
        flexWrap: 'wrap',
        gap: 10,
    },
    actionButton: {
        backgroundColor: colors.primary,
        paddingHorizontal: 25,
        paddingVertical: 12,
        borderRadius: 25,
        elevation: 3,
        minWidth: 120,
        alignItems: 'center',
        ...(isWeb && {
            cursor: 'pointer',
        }),
    },
    actionButtonText: {
        color: colors.white,
        fontSize: 16,
        fontWeight: 'bold',
    },
    infoButton: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 20,
        elevation: 2,
        minWidth: 100,
        alignItems: 'center',
        ...(isWeb && {
            cursor: 'pointer',
        }),
    },
    infoButtonText: {
        color: colors.white,
        fontSize: 14,
        fontWeight: '600',
        textAlign: 'center',
    },
    dominantContainer: {
        marginTop: 20,
        padding: 12,
        backgroundColor: colors.surfaceLight,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border,
    },
    dominantText: {
        fontSize: 14,
        color: colors.textSecondary,
        textAlign: 'center',
    },
    loadingContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 40,
    },
    loadingText: {
        marginTop: 20,
        fontSize: 16,
        color: colors.textMuted,
    },
    // ===== CURRENT AQI CARD =====
    currentAQICard: {
        backgroundColor: colors.surface,
        borderRadius: 16,
        padding: 25,
        alignItems: 'center',
        marginBottom: 25,
        width: '100%',
        ...(isWeb && {
            boxShadow: '0px 4px 12px rgba(0,0,0,0.12)',
        }),
    },

    // ===== MODAL STYLES =====
    modalOverlay: {
        flex: 1,
        backgroundColor: colors.overlay,
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: colors.surface,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 20,
        maxHeight: height * 0.85,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: colors.borderLighter,
        paddingBottom: 15,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.text,
    },
    closeButton: {
        fontSize: 18,
        color: colors.primary,
        fontWeight: 'bold',
        padding: 5,
        ...(isWeb && {
            cursor: 'pointer',
        }),
    },
    section: {
        marginBottom: 20,
        padding: 15,
        backgroundColor: colors.surfaceLighter,
        borderRadius: 10,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.text,
        marginBottom: 10,
    },
    pollutantRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: colors.borderLighter,
    },
    pollutantLabel: {
        fontSize: 14,
        color: colors.textMuted,
        flex: 2,
    },
    pollutantValue: {
        fontSize: 14,
        fontWeight: '600',
        flex: 1,
        textAlign: 'right',
    },
    infoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 6,
    },
    infoLabel: {
        fontSize: 14,
        color: colors.textMuted,
    },
    infoValue: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.text,
    },
    healthSection: {
        backgroundColor: '#e8f4fd',
        padding: 15,
        borderRadius: 10,
        marginBottom: 20,
    },
    healthText: {
        fontSize: 14,
        color: colors.text,
        lineHeight: 20,
    },
    forecastTable: {
        marginTop: 20,
        backgroundColor: colors.surfaceLighter,
        borderRadius: 10,
        padding: 15,
    },
    tableHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderBottomWidth: 2,
        borderBottomColor: colors.border,
        paddingBottom: 10,
        marginBottom: 10,
    },
    tableHeaderText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: colors.text,
        flex: 1,
        textAlign: 'center',
    },
    tableRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: colors.borderLighter,
    },
    tableCell: {
        fontSize: 12,
        color: colors.textMuted2,
        flex: 1,
        textAlign: 'center',
    },

    // ===== CURRENT LOCATION CARD IN MODAL =====
    currentLocationCard: {
        backgroundColor: colors.pale,
        borderRadius: 12,
        padding: 15,
        marginBottom: 20,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.borderLight,
    },
    currentLocationTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 10,
    },
    currentAQIBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 25,
        minWidth: 150,
        justifyContent: 'center',
    },
    currentAQIText: {
        color: colors.white,
        fontSize: 18,
        fontWeight: 'bold',
        marginRight: 10,
    },
    currentAQILevel: {
        color: colors.white,
        fontSize: 14,
        fontWeight: '600',
    },
    // ===== NEARBY STATIONS MODAL =====
    stationsList: {
        paddingBottom: 20,
    },
    stationsCount: {
        fontSize: 14,
        color: colors.textMuted,
        marginBottom: 15,
        textAlign: 'center',
        fontStyle: 'italic',
    },
    stationCard: {
        backgroundColor: colors.surface,
        borderRadius: 12,
        padding: 15,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: colors.surfaceLight,
        ...(isWeb && {
            cursor: 'pointer',
            boxShadow: '0px 2px 6px rgba(0,0,0,0.10)',
            transition: 'transform 0.2s',
            ':hover': {
                transform: [{ translateY: -2 }],
            },
        }),
    },
    stationHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    stationIndex: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: colors.paleBlue,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    stationIndexText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: colors.accentBlue,
    },
    stationInfo: {
        flex: 1,
    },
    stationName: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 4,
    },
    stationDistance: {
        fontSize: 12,
        color: colors.textMuted,
    },
    stationAQISection: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    aqiBadge: {
        paddingHorizontal: 20,
        paddingVertical: 8,
        borderRadius: 20,
        minWidth: 80,
        alignItems: 'center',
    },
    aqiValue: {
        color: colors.white,
        fontSize: 20,
        fontWeight: 'bold',
    },
    aqiLevelText: {
        fontSize: 14,
        color: colors.textSecondary,
        fontWeight: '600',
    },
    stationFooter: {
        borderTopWidth: 1,
        borderTopColor: colors.background,
        paddingTop: 10,
    },
    stationCoordinates: {
        fontSize: 11,
        color: colors.textMuted2,
        textAlign: 'center',
    },
    noStationsContainer: {
        padding: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    noStationsText: {
        fontSize: 16,
        color: colors.textMuted3,
        textAlign: 'center',
    },
    backButton: {
        backgroundColor: colors.backButton,
        paddingVertical: 12,
        borderRadius: 25,
        alignItems: 'center',
        marginTop: 20,
        ...(isWeb && {
            cursor: 'pointer',
        }),
    },
    backButtonText: {
        color: colors.white,
        fontSize: 16,
        fontWeight: '600',
    },
    stationsPreviewContainer: {
        backgroundColor: colors.surface,
        borderRadius: 16,
        padding: 15,
        marginTop: 20,
        width: '100%',
        ...(isWeb && {
            boxShadow: '0px 3px 10px rgba(0,0,0,0.15)',
        }),
    },
    stationsPreviewHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    stationsPreviewTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
    },
    viewAllButton: {
        backgroundColor: colors.surfaceLight,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 15,
        ...(isWeb && {
            cursor: 'pointer',
        }),
    },
    viewAllText: {
        fontSize: 12,
        color: colors.textMuted,
        fontWeight: '500',
    },
    stationsHorizontalScroll: {
        minHeight: 180,
        ...(isWeb && {
            '::-webkit-scrollbar': {
                height: '6px',
            },
            '::-webkit-scrollbar-track': {
                background: colors.background,
                borderRadius: 3,
            },
            '::-webkit-scrollbar-thumb': {
                background: colors.primary,
                borderRadius: 3,
            },
        }),
    },
    stationsScrollContent: {
        paddingHorizontal: 5,
        paddingBottom: 10,
    },
    stationPreviewCard: {
        width: 140,
        backgroundColor: colors.pale,
        borderRadius: 12,
        padding: 12,
        marginRight: 10,
        borderWidth: 1,
        borderColor: colors.borderLight,
        elevation: 2,
        ...(isWeb && {
            cursor: 'pointer',
            transition: 'transform 0.2s',
            ':hover': {
                transform: [{ translateY: -2 }],
            },
        }),
    },
    stationCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    stationNumberBadge: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: colors.paleBlue,
        justifyContent: 'center',
        alignItems: 'center',
    },
    stationNumberText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: colors.accentBlue,
    },
    aqiIndicator: {
        width: 12,
        height: 12,
        borderRadius: 6,
    },
    stationNamePreview: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 8,
        height: 36,
    },
    stationInfoPreview: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    stationDistancePreview: {
        fontSize: 11,
        color: colors.textMuted,
    },
    aqiBadgePreview: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        minWidth: 45,
        alignItems: 'center',
    },
    aqiValuePreview: {
        color: colors.white,
        fontSize: 14,
        fontWeight: 'bold',
    },
    stationLevelPreview: {
        fontSize: 11,
        color: colors.textMuted,
        textAlign: 'center',
        fontStyle: 'italic',
    },

    // City header with favorite
    cityHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    locationsButton: {
        marginLeft: 10,
        padding: 5,
    },
    locationIcon: {
        fontSize: 24,
        marginBottom: 20,
    },
    savedLocationsList: {
        paddingBottom: 20,
    },
    savedLocationItem: {
        flexDirection: 'row',
        backgroundColor: colors.surface,
        borderRadius: 12,
        padding: 15,
        marginBottom: 10,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
        elevation: 2,
        shadowColor: colors.shadow,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    savedLocationContent: {
        flex: 1,
    },
    savedLocationCity: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 5,
    },
    savedLocationDetails: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 5,
    },
    savedLocationAqiBadge: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 15,
    },
    savedLocationAqiText: {
        color: colors.white,
        fontSize: 12,
        fontWeight: '600',
    },
    savedLocationLevel: {
        fontSize: 12,
        color: colors.textMuted,
        fontStyle: 'italic',
    },
    savedLocationTime: {
        fontSize: 10,
        color: colors.textMuted2,
    },
    removeSavedLocationButton: {
        padding: 10,
    },
    removeSavedLocationText: {
        fontSize: 18,
        color: colors.danger,
        fontWeight: 'bold',
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 40,
    },
    emptyStateText: {
        fontSize: 18,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 10,
    },
    emptyStateSubtext: {
        fontSize: 14,
        color: colors.textMuted,
        textAlign: 'center',
        paddingHorizontal: 20,
    },
});